apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps
  name: svelte-app-deployment
  labels:
    app: svelte-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svelte-app
  template:
    metadata:
      labels:
        app: svelte-app
    spec:
      containers:
      - name: svelte-app
        image: registry.digitalocean.com/containers/workshop-github-actions-test:latest
        ports:
        - containerPort: 5173